"""Derive disjoint bed/bank meshes from the accepted contour; no wet PNGs."""
from pathlib import Path
import numpy as np, hashlib
from PIL import Image, ImageFilter
root=Path(__file__).resolve().parents[1]
(root/'TestResults').mkdir(exist_ok=True)
source=root/'Art/Sources/Terrain/AMJW/Canal'
script=(source/'build_tiles_reference.py').read_text(encoding='utf-8-sig')
script=script[script.index('SIZE,SS='):script.index('def pngcheck')]
script=script.replace("OUT=ROOT/'PNG'", "OUT=ROOT/'TestResults/ArtScratch'")
script=script.replace("shutil.copyfile(SRC,ROOT/'Sources'/'ReferenceMaster.png')",'')
script=script.replace("(ROOT/'Sources').mkdir(exist_ok=True)",'')
ns=dict(ROOT=root,SRC=source/'ReferenceMaster.png',np=np,Image=Image,ImageFilter=ImageFilter,hashlib=hashlib)
exec(script,ns)
def runs(support):
    rows=[]; active={}
    for y in range(128):
        a=np.flatnonzero(support[y])
        current={}
        if len(a):
            for group in np.split(a,np.flatnonzero(np.diff(a)!=1)+1):
                row=(int(group[0]),int(group[-1])+1)
                current[row]=(row[0],row[1],active[row][2] if row in active else y,y+1)
        rows.extend(rect for key,rect in active.items() if key not in current)
        active=current
    rows.extend(active.values())
    reconstructed=np.zeros_like(support)
    for x0,x1,y0,y1 in rows: reconstructed[y0:y1,x0:x1]=True
    assert np.array_equal(reconstructed,support)
    return ', '.join(str(v) for row in rows for v in row)
beds=[ns['render'](m)[2] for m in range(16)]
lines=['// Generated by Scripts/export-canal-bed.py from accepted contour.',
       'namespace AncientMedievalJapan.Waterworks {','public static class CanalBedGeometry {']
for label,complement in [('Runs',False),('Banks',True)]:
    lines.append('public static readonly int[][] '+label+' = new int[][] {')
    for mask,bed in enumerate(beds):
        support=~bed if complement else bed
        lines.append('new int[] { '+runs(support)+' }, // '+str(mask))
    lines.append('};')
lines.append('}}')
(root/'Source/CanalBedGeometry.cs').write_text('\n'.join(lines)+'\n',encoding='utf-8')
print('16 exact complementary bed/bank meshes exported; accepted PNGs unchanged.')
