"""Export accepted dry art bed support as geometry, never a wet PNG."""
from pathlib import Path
import numpy as np, hashlib
from PIL import Image, ImageFilter
root=Path(__file__).resolve().parents[1]
(root/'TestResults').mkdir(exist_ok=True)
source=root/'Art/Sources/Terrain/AMJW/Canal'
script=(source/'build_tiles_reference.py').read_text(encoding='utf-8-sig')
script=script[script.index('SIZE,SS='):script.index('def pngcheck')]
script=script.replace("OUT=ROOT/'PNG'", "OUT=ROOT/'TestResults/ArtScratch'")
script=script.replace("shutil.copyfile(SRC,ROOT/'Sources'/'ReferenceMaster.png')",'')
script=script.replace("(ROOT/'Sources').mkdir(exist_ok=True)",'')
ns=dict(ROOT=root,SRC=source/'ReferenceMaster.png',np=np,Image=Image,ImageFilter=ImageFilter,hashlib=hashlib)
exec(script,ns)
lines=['// Generated by Scripts/export-canal-bed.py from accepted contour.','namespace AncientMedievalJapan.Waterworks {','public static class CanalBedGeometry {','public static readonly int[][] Runs = new int[][] {']
for mask in range(16):
    _,_,bed=ns['render'](mask)
    rows=[]
    for y in range(128):
        a=np.flatnonzero(bed[y])
        if len(a):
            for group in np.split(a,np.flatnonzero(np.diff(a)!=1)+1):
                row=(int(group[0]),int(group[-1])+1)
                if rows and rows[-1][0:2]==row and rows[-1][3]==y:
                    rows[-1]=(row[0],row[1],rows[-1][2],y+1)
                else: rows.append((row[0],row[1],y,y+1))
    reconstructed=np.zeros_like(bed)
    for x0,x1,y0,y1 in rows: reconstructed[y0:y1,x0:x1]=True
    assert np.array_equal(reconstructed,bed), 'Bed geometry must preserve every support pixel'
    lines.append('new int[] { '+', '.join(str(v) for row in rows for v in row)+' }, // '+str(mask))
lines+=['};','}}']
(root/'Source/CanalBedGeometry.cs').write_text('\n'.join(lines)+'\n',encoding='utf-8')
print('Exported 16 bed meshes; no water texture created.')
